// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata (App Router)
export const metadata = {
  title: "Training and placement",
  description: "Generated by Training and placement",
  // icons tells Next.js which icons to include (OG/manifest handled separately)
  icons: {
    icon: "/pcl.ico",                 // default pcl
    shortcut: "/pcl-32x32.png",       // used for shortcut link
    apple: "/apple-touch-icon.png",       // apple touch icon
    other: [
      { rel: "icon", url: "/pcl-16x16.png", sizes: "16x16", type: "image/png" },
      { rel: "icon", url: "/pcl-32x32.png", sizes: "32x32", type: "image/png" },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* You may include additional head tags here (manifest, theme-color) */}
      <head>
        {/* Progressive Web App manifest */}
        <link rel="manifest" href="/site.webmanifest" />
        {/* Theme color for mobile browser address bar */}
        <meta name="theme-color" content="#0ea5e9" />
        {/* optional: force legacy pcl links (not required if metadata.icons used) */}
        <link rel="icon" href="/pcl.ico" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}





// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
